import numpy as np

import pandas as pd

from colorama import Fore, Style, init

init()

Green = Fore.GREEN

Red = Fore.RED

Yellow = Fore.YELLOW

Blue = Fore.BLUE

Cyan = Fore.CYAN

Magenta = Fore.MAGENTA

White = Fore.WHITE

Reset = Style.RESET_ALL

Bold = Style.BRIGHT

# Reading the already cleaned cafe sales file for analysis(after cleaning in cleaning.py).
clean_dataframe = pd.read_csv("data/cleaned/clean_cafe_sales.csv")

# The date was cleaned by me and converted to datetime in cleaning.py.
# But after saving the data as CSV and reading it again with read_csv(),
# Pandas may treat the dates as normal text/object values.
# Converting it again to datetime allows me to use .dt.month, .dt.date, etc.
clean_dataframe["Transaction Date"] = pd.to_datetime(
    clean_dataframe["Transaction Date"]
)

# Main heading for the complete analysis report.
print(f"{Magenta}{Bold}\n\n\t\t\t\t\t\t======================================={Reset}")

print(f"{Magenta}{Bold}\t\t\t\t\t\t\tRaw2Insight - Analysis{Reset}")

print(f"{Magenta}{Bold}\t\t\t\t\t\t======================================={Reset}")


# Section 1 contains the overall information about the cafe sales.
print(f"{Cyan}{Bold}\n\n======================================={Reset}")

print(f"{Cyan}{Bold}\t1. Overall Sales Overview{Reset}")

print(f"{Cyan}{Bold}======================================={Reset}")

print(f"{Bold}\n------------------------------------------------\n{Reset}")

# shape[0] gives the total number of rows/transactions in the dataset.
print(f"{Bold}Total number of transactions:  {Green}{clean_dataframe.shape[0]}{Reset}")

# Adding the Quantity column gives the total number of items sold.
print(f"{Bold}Total quantity sold:  {Green}{clean_dataframe['Quantity'].sum()}{Reset}")

# Sum of Total Spent gives the total sales/revenue of all transactions.
print(
    f"{Bold}Total revenue / total sales:  {Green}${clean_dataframe['Total Spent'].sum():.2f}{Reset}"
)

# Mean of Total Spent gives the average amount spent in one transaction.
print(
    f"{Bold}Average transaction value:  {Green}${clean_dataframe['Total Spent'].mean():.2f}{Reset}"
)

# Mean quantity shows the average number of items purchased in a transaction.
print(
    f"{Bold}Average quantity per transaction:  {Green}{clean_dataframe['Quantity'].mean():.0f}{Reset}"
)

# Finding the smallest and largest transaction values.
print(
    f"{Bold}Minimum transaction value:  {Green}${clean_dataframe['Total Spent'].min():.2f}{Reset}"
)

print(
    f"{Bold}Maximum transaction value:  {Green}${clean_dataframe['Total Spent'].max():.2f}{Reset}"
)

print(f"{Bold}\n------------------------------------------------{Reset}")


# Section 2 analyzes sales performance for each individual cafe item.
print(f"{Cyan}{Bold}\n\n======================================={Reset}")

print(f"{Cyan}{Bold}\t2. Item Analysis{Reset}")

print(f"{Cyan}{Bold}======================================={Reset}")

print(f"{Bold}\n------------------------------------------------\n{Reset}")

print(f"{Bold}{Yellow}Number of transactions per item:  {Reset}\n")

# Grouping by Item and counting Transaction IDs shows how many transactions each item has.
print(f"{Bold}{clean_dataframe.groupby('Item')['Transaction ID'].count()}{Reset}")

print(f"{Bold}{Yellow}\nTotal quantity sold per item:  {Reset}\n")

# Grouping by Item and summing Quantity gives the total units sold for each item.
print(f"{Bold}{clean_dataframe.groupby('Item')['Quantity'].sum()}{Reset}")

print(f"{Bold}{Yellow}\nTotal revenue generated by each item:  {Reset}\n")

# Grouping by Item and summing Total Spent gives the total revenue for each item.
# map() is used to format every revenue value with a dollar sign and two decimal places.
print(
    f"{Bold}{clean_dataframe.groupby('Item')['Total Spent'].sum().map(lambda x: f'$ {x:,.2f}')}{Reset}"
)

print(f"{Bold}{Yellow}\nAverage price per unit for each item:  {Reset}\n")

# Finding the average unit price separately for every item.
print(f"{Bold}{clean_dataframe.groupby('Item')['Price Per Unit'].mean()}{Reset}")

# idxmax() returns the item name that has the highest total quantity sold.
print(f"{Bold}{Yellow}\nHighest selling item by quantity:  {Reset}", end="")

print(f"{Bold}{clean_dataframe.groupby('Item')['Quantity'].sum().idxmax()}{Reset}")

# idxmax() returns the item name that generated the highest total revenue.
print(f"{Bold}{Yellow}\nHighest-revenue item:  {Reset}", end="")

print(f"{Bold}{clean_dataframe.groupby('Item')['Total Spent'].sum().idxmax()}{Reset}")

# idxmin() returns the item name with the lowest total quantity sold.
print(f"{Bold}{Yellow}\nLowest selling item by quantity:  {Reset}", end="")

print(f"{Bold}{clean_dataframe.groupby('Item')['Quantity'].sum().idxmin()}{Reset}")

# idxmin() returns the item name with the lowest total revenue.
print(f"{Bold}{Yellow}\nLowest-revenue item:  {Reset}", end="")

print(f"{Bold}{clean_dataframe.groupby('Item')['Total Spent'].sum().idxmin()}{Reset}")

print(f"{Bold}\n------------------------------------------------{Reset}")


# Section 3 focuses on the quantity purchased in individual transactions.
print(f"{Cyan}{Bold}\n\n======================================={Reset}")

print(f"{Cyan}{Bold}\t3. Quantity Analysis{Reset}")

print(f"{Cyan}{Bold}======================================={Reset}")

print(f"{Bold}\n------------------------------------------------\n{Reset}")

# Total number of items sold across all transactions.
print(
    f"{Bold}{Yellow}Total quantity sold:{Reset} {Bold}{clean_dataframe['Quantity'].sum()}{Reset}"
)

# Average number of items purchased in one transaction.
print(
    f"\n{Bold}{Yellow}Average quantity per transaction:{Reset} {Bold}{clean_dataframe['Quantity'].mean():.0f}{Reset}"
)

# Minimum and maximum quantities show the range of items purchased in a single transaction.
print(
    f"\n{Bold}{Yellow}Minimum quantity sold in a transaction:{Reset} {Bold}{clean_dataframe['Quantity'].min()}{Reset}"
)

print(
    f"\n{Bold}{Yellow}Maximum quantity sold in a transaction:{Reset} {Bold}{clean_dataframe['Quantity'].max()}{Reset}"
)

# mode()[0] gives the quantity that appears most frequently in the dataset.
print(
    f"\n{Bold}{Yellow}Most commonly purchased quantity:{Reset} {Bold}{clean_dataframe['Quantity'].mode()[0]}{Reset}"
)

print(f"{Bold}\n------------------------------------------------{Reset}")


print(f"{Cyan}{Bold}\n\n======================================={Reset}")

print(f"{Cyan}{Bold}\t4. Payment Method Analysis{Reset}")

print(f"{Cyan}{Bold}======================================={Reset}")

print(f"{Bold}\n------------------------------------------------\n{Reset}")

# Grouping by payment method allows me to compare transaction volume,
# revenue, and quantity for each payment method.
print(f"{Bold}{Yellow}Number of transactions per payment method:  {Reset}\n")

print(
    f"{Bold}{clean_dataframe.groupby('Payment Method')['Transaction ID'].count()}{Reset}"
)

print(f"\n{Bold}{Yellow}Revenue by payment method:  {Reset}\n")

print(
    f"{Bold}{clean_dataframe.groupby('Payment Method')['Total Spent'].sum().map(lambda x: f'$ {x:,.2f}')}{Reset}"
)

print(f"\n{Bold}{Yellow}Quantity by payment method:  {Reset}\n")

print(f"{Bold}{clean_dataframe.groupby('Payment Method')['Quantity'].sum()}{Reset}")

print(f"{Bold}\n------------------------------------------------{Reset}")


print(f"{Cyan}{Bold}\n\n======================================={Reset}")

print(f"{Cyan}{Bold}\t5. Location Analysis{Reset}")

print(f"{Cyan}{Bold}======================================={Reset}")

print(f"{Bold}\n------------------------------------------------\n{Reset}")

# Grouping by location shows how transactions, revenue, and quantity
# are distributed between the two cafe locations.
print(f"{Bold}{Yellow}Number of transactions per location:  {Reset}\n")

print(f"{Bold}{clean_dataframe.groupby('Location')['Transaction ID'].count()}{Reset}")

print(f"{Bold}{Yellow}\nRevenue by location:  {Reset}\n")

print(
    f"{Bold}{clean_dataframe.groupby('Location')['Total Spent'].sum().map(lambda x: f'$ {x:,.2f}')}{Reset}"
)

print(f"{Bold}{Yellow}\nQuantity by location:  {Reset}\n")

print(f"{Bold}{clean_dataframe.groupby('Location')['Quantity'].sum()}{Reset}")

print(f"{Bold}\n------------------------------------------------{Reset}")


print(f"{Cyan}{Bold}\n\n==========================================={Reset}")

print(f"{Cyan}{Bold}\t6. Transaction-Date Analysis{Reset}")

print(f"{Cyan}{Bold}==========================================={Reset}")

print(f"{Bold}\n------------------------------------------------\n{Reset}")

print(f"{Bold}{Yellow}Number of transactions per month:  {Reset}\n")

# .dt.month extracts the month number from each transaction date.
# Since this dataset covers only 2023, each month number represents
# one unique month in the dataset, from January (1) to December (12).
print(f"{Bold} {clean_dataframe.groupby(
        clean_dataframe["Transaction Date"].dt.month
    )["Transaction ID"].count()
}{Reset}")

print(f"\n{Bold}{Yellow}Revenue per month:  {Reset}\n")

# Grouping by month and summing Total Spent shows the revenue generated
# in each month and helps identify the strongest month.
print(
    f"{Bold}{clean_dataframe.groupby(clean_dataframe['Transaction Date'].dt.month)['Total Spent'].sum().map(lambda x: f'$ {x:,.2f}')}{Reset}"
)

print(f"\n{Bold}{Yellow}Quantity Sold per month:  {Reset}\n")

# Grouping by month and summing Quantity shows how many items were sold
# during each month.
print(
    f"{Bold}{clean_dataframe.groupby(clean_dataframe['Transaction Date'].dt.month)['Quantity'].sum()}{Reset}"
)

print(f"\n{Bold}{Yellow}Highest Revenue Day:  {Reset}\n")

# .dt.date gives the complete date, such as 2023-12-31.
# I use the complete date instead of .dt.day because the day number
# repeats every month. For example, day 15 appears in January, February,
# March, and other months. The complete date is unique for this dataset.
print(
    f"{Bold}{clean_dataframe.groupby(clean_dataframe['Transaction Date'].dt.date)['Total Spent'].sum().idxmax()}{Reset}"
)

print(f"\n{Bold}{Yellow}Lowest Revenue Day:  {Reset}\n")

# Using the complete date here allows me to find the exact calendar day
# with the lowest total revenue instead of only finding a day number.
print(
    f"{Bold}{clean_dataframe.groupby(clean_dataframe['Transaction Date'].dt.date)['Total Spent'].sum().idxmin()}{Reset}"
)

print(f"{Bold}\n------------------------------------------------{Reset}")


# Final Analysis Insights:
# December was the strongest month in terms of transaction volume,
# total quantity sold, and total revenue.
#
# Salad generated the highest total revenue among the cafe items.
#
# Juice was the highest-selling item by total quantity.
#
# Potato Fries had the lowest transaction volume, quantity sold,
# and total revenue compared with the other items.
#
# The transaction-date analysis helped me understand how sales
# changed over time instead of looking only at the complete dataset.
#
# Overall, this analysis helped me use NumPy and Pandas for
# practical business analysis instead of only performing basic calculations.
